# Site settings
title: Christian Seidle
description: >- # this means to ignore newlines until "baseurl:"
  Overview of my github projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ckseidle.github.io" # the base hostname & protocol for your site

# Optional settings
# You can uncomment these lines to customize your site further
#twitter_username: your_twitter_username
#github_username:  your_github_username

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Minima theme settings
minima:
  include:
    - index.md
    - about.md
    - contact.md
  exclude:
    - README.md
  # To customize the theme, you can override these defaults in your own _config.yml:
  # skin: default
  # social_links:
  #   twitter: your_twitter_username
  #   github:  your_github_username
  #   linkedin: your_linkedin_username

# Markdown settings
markdown: kramdown
highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Pagination settings
paginate: 5
paginate_path: "/page:num/"
